{{- $octopodAppAuthPassword := include "octopodUiAuthSecret" . -}}
{{- $etag := sha256sum (now | date "Mon Jan 2 15:04:05 MSK 2021") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "octopod.fullname" . }}-nginx-config
  labels:
    {{- include "octopod.labels" . | nindent 4 }}
data:
  app.conf: |
    server {
      listen 80 default_server;
      server_name _;
      root /www;
      index index.html;
      error_page 404 =200 /index.html;
      charset utf-8;
      location ~* \.(html|css|js|xml)$ {
        gzip_static on;
        add_header 'ETag' '{{ $etag }}';
      }
    }
  config.json: |
    {
      "app_url": "{{ printf "%s://%s" (include "httpScheme" .) (include "appIngressHost" . )}}",
      "ws_url": "{{ printf "%s://%s" (include "wsScheme" .) (include "wsIngressHost" .) }}",
      "app_auth": "Basic {{ printf "octopod:%s" $octopodAppAuthPassword | b64enc }}",
      {{- if .Values.kubernetesDashboard.enabled }}
      "kubernetes_dashboard_url_template": "{{ .Values.kubernetesDashboard.url }}/#/search?namespace={{ .Values.octopod.deploymentNamespace }}&q="
      {{- else }}
      "kubernetes_dashboard_url_template": null
      {{- end }}
    }
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "octopodAppAuthSecretName" . }}
  labels:
    {{- include "octopod.labels" . | nindent 4 }}
data:
  auth: {{ htpasswd "octopod" $octopodAppAuthPassword | b64enc }}
